- name: "Сменить порт по умолчанию"
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: "Listen {{ web_port }}"
  notify: "Перезапуск службы httpd"

- name: "Передача шаблона index.html"
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
  notify: "Перезапуск службы httpd"

- name: "Запуск обработчиков (handlers)"
  meta: flush_handlers

