- name: "Установка zsh"
  hosts: slaves
  become: yes
  tasks:
  - name: "Установка пакета"
    dnf:
      name: zsh
      state: latest

  - name: "Test my users module"
    users_list:
      new_shell: "/bin/bash"
      # old_shell: "/bin/zsh"
    
