---
- name: "Register vars"
  hosts: all
  # become: True
  gather_facts: yes

  tasks:
    # - name: "whoami"
    #   command: whoami
    #   register: login
    
    # - debug: var=login
    # - debug: msg="User {{ login.stdout }}"

    # - name: "Get file info"
    #   file:
    #     path: "/etc/fstab"
    #   register: fileinfo

    # - debug: var=fileinfo
    # - debug: msg="File owner {{ fileinfo.owner }}"

    - name: "Get local fact"
      debug: var=ansible_local
    #   debug: msg="node_name {{ ansible_local.example.test.node_name }}"

    # - name: "Получение информации о службах"
    #   ansible.builtin.service_facts:

    # - name: "Set NetworkManager state"
    #   when: ansible_facts['services']['sshd.service']['state'] is defined
    #   set_fact:
    #     NM_state: "{{ ansible_facts['services']['NetworkManager.service']['state'] }}"

    - debug: var=inventory_hostname
    - debug: var=groups
    # groups, ansible_check_mode, ansible_play_batch, ansible_play_hosts, hostvars
