- name: "Create users"
  hosts: slaves
  become: True
  vars_files:
    - ../vault

  tasks:
  - name: 'Create users from list'
    user:
      name: "{{ item }}"
      create_home: yes
      password: "{{ user_pass | password_hash('sha512') }}"
      append: yes
      groups: users, wheel
    loop: "{{ users }}"

